/*
 * StockX - Bachelor Project
 *
 * This API is developed for a Bachelor Project Application named StockX.   - It both projects current stock market data and works as a learning tool while doing fake stock trading.    Authors of the project - Aleksander Stefan Bialik - Konrad Piotrowski  
 *
 * API version: 1.0.0
 * Contact: 280053@via.dk
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RegisterUser struct {

	Email string `json:"email"`

	Password string `json:"password"`
}
