/*
 * StockX - Bachelor Project
 *
 * This API is developed for a Bachelor Project Application named StockX.   - It both projects current stock market data and works as a learning tool while doing fake stock trading.    Authors of the project - Aleksander Stefan Bialik - Konrad Piotrowski  
 *
 * API version: 1.0.0
 * Contact: 280053@via.dk
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/k0k0piotrowski/StockX/1.0.0/",
		Index,
	},

	Route{
		"LoginUser",
		strings.ToUpper("Post"),
		"/k0k0piotrowski/StockX/1.0.0/auth/login",
		LoginUser,
	},

	Route{
		"RegisterUser",
		strings.ToUpper("Post"),
		"/k0k0piotrowski/StockX/1.0.0/auth/register",
		RegisterUser,
	},

	Route{
		"UserSettingsGet",
		strings.ToUpper("Get"),
		"/k0k0piotrowski/StockX/1.0.0/user/settings",
		UserSettingsGet,
	},
}
