/*
 * StockX - Bachelor Project
 *
 * This API is developed for a Bachelor Project Application named StockX.   - It both projects current stock market data and works as a learning tool while doing fake stock trading.    Authors of the project - Aleksander Stefan Bialik - Konrad Piotrowski
 *
 * API version: 1.0.0
 * Contact: 280053@via.dk
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package logger

import (
	"log"
	"net/http"
	"time"
)

func Logger(inner http.Handler, name string) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()

		inner.ServeHTTP(w, r)

		log.Printf(
			"%s %s %s %s",
			r.Method,
			r.RequestURI,
			name,
			time.Since(start),
		)
	})
}
